/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampeonatosIdRouteImport } from './routes/campeonatos.$id'
import { Route as CampeonatosIdPublicoRouteImport } from './routes/campeonatos.$id.publico'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIdRoute = CampeonatosIdRouteImport.update({
  id: '/campeonatos/$id',
  path: '/campeonatos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIdPublicoRoute = CampeonatosIdPublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => CampeonatosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/$id/publico': typeof CampeonatosIdPublicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/$id/publico': typeof CampeonatosIdPublicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/$id/publico': typeof CampeonatosIdPublicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/inscricoes'
    | '/login'
    | '/campeonatos/$id'
    | '/campeonatos/$id/publico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/inscricoes'
    | '/login'
    | '/campeonatos/$id'
    | '/campeonatos/$id/publico'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/inscricoes'
    | '/login'
    | '/campeonatos/$id'
    | '/campeonatos/$id/publico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  InscricoesRoute: typeof InscricoesRoute
  LoginRoute: typeof LoginRoute
  CampeonatosIdRoute: typeof CampeonatosIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$id': {
      id: '/campeonatos/$id'
      path: '/campeonatos/$id'
      fullPath: '/campeonatos/$id'
      preLoaderRoute: typeof CampeonatosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$id/publico': {
      id: '/campeonatos/$id/publico'
      path: '/publico'
      fullPath: '/campeonatos/$id/publico'
      preLoaderRoute: typeof CampeonatosIdPublicoRouteImport
      parentRoute: typeof CampeonatosIdRoute
    }
  }
}

interface CampeonatosIdRouteChildren {
  CampeonatosIdPublicoRoute: typeof CampeonatosIdPublicoRoute
}

const CampeonatosIdRouteChildren: CampeonatosIdRouteChildren = {
  CampeonatosIdPublicoRoute: CampeonatosIdPublicoRoute,
}

const CampeonatosIdRouteWithChildren = CampeonatosIdRoute._addFileChildren(
  CampeonatosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  InscricoesRoute: InscricoesRoute,
  LoginRoute: LoginRoute,
  CampeonatosIdRoute: CampeonatosIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
