/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipesIdRouteImport } from './routes/equipes.$id'
import { Route as CampeonatosVisualizarRouteImport } from './routes/campeonatos.visualizar'
import { Route as CampeonatosNovoRouteImport } from './routes/campeonatos.novo'
import { Route as CampeonatosIdRouteImport } from './routes/campeonatos.$id'
import { Route as CampeonatosIdPublicoRouteImport } from './routes/campeonatos.$id.publico'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesIdRoute = EquipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipesRoute,
} as any)
const CampeonatosVisualizarRoute = CampeonatosVisualizarRouteImport.update({
  id: '/campeonatos/visualizar',
  path: '/campeonatos/visualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosNovoRoute = CampeonatosNovoRouteImport.update({
  id: '/campeonatos/novo',
  path: '/campeonatos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIdRoute = CampeonatosIdRouteImport.update({
  id: '/campeonatos/$id',
  path: '/campeonatos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIdPublicoRoute = CampeonatosIdPublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => CampeonatosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/equipes': typeof EquipesRouteWithChildren
  '/feed': typeof FeedRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/novo': typeof CampeonatosNovoRoute
  '/campeonatos/visualizar': typeof CampeonatosVisualizarRoute
  '/equipes/$id': typeof EquipesIdRoute
  '/campeonatos/$id/publico': typeof CampeonatosIdPublicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/equipes': typeof EquipesRouteWithChildren
  '/feed': typeof FeedRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/novo': typeof CampeonatosNovoRoute
  '/campeonatos/visualizar': typeof CampeonatosVisualizarRoute
  '/equipes/$id': typeof EquipesIdRoute
  '/campeonatos/$id/publico': typeof CampeonatosIdPublicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/equipes': typeof EquipesRouteWithChildren
  '/feed': typeof FeedRoute
  '/inscricoes': typeof InscricoesRoute
  '/login': typeof LoginRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/novo': typeof CampeonatosNovoRoute
  '/campeonatos/visualizar': typeof CampeonatosVisualizarRoute
  '/equipes/$id': typeof EquipesIdRoute
  '/campeonatos/$id/publico': typeof CampeonatosIdPublicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/equipes'
    | '/feed'
    | '/inscricoes'
    | '/login'
    | '/campeonatos/$id'
    | '/campeonatos/novo'
    | '/campeonatos/visualizar'
    | '/equipes/$id'
    | '/campeonatos/$id/publico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/equipes'
    | '/feed'
    | '/inscricoes'
    | '/login'
    | '/campeonatos/$id'
    | '/campeonatos/novo'
    | '/campeonatos/visualizar'
    | '/equipes/$id'
    | '/campeonatos/$id/publico'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/equipes'
    | '/feed'
    | '/inscricoes'
    | '/login'
    | '/campeonatos/$id'
    | '/campeonatos/novo'
    | '/campeonatos/visualizar'
    | '/equipes/$id'
    | '/campeonatos/$id/publico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  EquipesRoute: typeof EquipesRouteWithChildren
  FeedRoute: typeof FeedRoute
  InscricoesRoute: typeof InscricoesRoute
  LoginRoute: typeof LoginRoute
  CampeonatosIdRoute: typeof CampeonatosIdRouteWithChildren
  CampeonatosNovoRoute: typeof CampeonatosNovoRoute
  CampeonatosVisualizarRoute: typeof CampeonatosVisualizarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes/$id': {
      id: '/equipes/$id'
      path: '/$id'
      fullPath: '/equipes/$id'
      preLoaderRoute: typeof EquipesIdRouteImport
      parentRoute: typeof EquipesRoute
    }
    '/campeonatos/visualizar': {
      id: '/campeonatos/visualizar'
      path: '/campeonatos/visualizar'
      fullPath: '/campeonatos/visualizar'
      preLoaderRoute: typeof CampeonatosVisualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/novo': {
      id: '/campeonatos/novo'
      path: '/campeonatos/novo'
      fullPath: '/campeonatos/novo'
      preLoaderRoute: typeof CampeonatosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$id': {
      id: '/campeonatos/$id'
      path: '/campeonatos/$id'
      fullPath: '/campeonatos/$id'
      preLoaderRoute: typeof CampeonatosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$id/publico': {
      id: '/campeonatos/$id/publico'
      path: '/publico'
      fullPath: '/campeonatos/$id/publico'
      preLoaderRoute: typeof CampeonatosIdPublicoRouteImport
      parentRoute: typeof CampeonatosIdRoute
    }
  }
}

interface EquipesRouteChildren {
  EquipesIdRoute: typeof EquipesIdRoute
}

const EquipesRouteChildren: EquipesRouteChildren = {
  EquipesIdRoute: EquipesIdRoute,
}

const EquipesRouteWithChildren =
  EquipesRoute._addFileChildren(EquipesRouteChildren)

interface CampeonatosIdRouteChildren {
  CampeonatosIdPublicoRoute: typeof CampeonatosIdPublicoRoute
}

const CampeonatosIdRouteChildren: CampeonatosIdRouteChildren = {
  CampeonatosIdPublicoRoute: CampeonatosIdPublicoRoute,
}

const CampeonatosIdRouteWithChildren = CampeonatosIdRoute._addFileChildren(
  CampeonatosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  EquipesRoute: EquipesRouteWithChildren,
  FeedRoute: FeedRoute,
  InscricoesRoute: InscricoesRoute,
  LoginRoute: LoginRoute,
  CampeonatosIdRoute: CampeonatosIdRouteWithChildren,
  CampeonatosNovoRoute: CampeonatosNovoRoute,
  CampeonatosVisualizarRoute: CampeonatosVisualizarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
